name: Update Singbox Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 12 点执行
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果有依赖的话

      - name: Run Singbox script
        run: |
          python Singbox.py  # 运行你的脚本

      - name: Commit and push changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add output.srs  # 添加生成的 .srs 文件
          git commit -m "Update Singbox rules"
          git push
